//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaenggiModel.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaenggiModel.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antero Inferior:.
        /// </summary>
        public static string AnteroInferior {
            get {
                return ResourceManager.GetString("AnteroInferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antero Superior:.
        /// </summary>
        public static string AnteroSuperior {
            get {
                return ResourceManager.GetString("AnteroSuperior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haenggi Mediciones Dentales.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long. Arco:.
        /// </summary>
        public static string ArchLong {
            get {
                return ResourceManager.GetString("ArchLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolton.
        /// </summary>
        public static string BoltonTitle {
            get {
                return ResourceManager.GetString("BoltonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolton Total  -&gt; .
        /// </summary>
        public static string BoltonTotal {
            get {
                return ResourceManager.GetString("BoltonTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibracion.
        /// </summary>
        public static string CalibrationTitle {
            get {
                return ResourceManager.GetString("CalibrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Junte las puntas del instrumento y a continuación mantenga apretado el boton hasta que cambie a color azul.
        /// </summary>
        public static string CalibratorFirstStep {
            get {
                return ResourceManager.GetString("CalibratorFirstStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Utilice el cilindro 10mm sujetelo entre las puntas, presione el botón y  verifique el resultado:.
        /// </summary>
        public static string CalibratorSecondStep {
            get {
                return ResourceManager.GetString("CalibratorSecondStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) Utilice el cilindro 20mm sujetelo entre las puntas, presione el botón y el verifique el resultado:.
        /// </summary>
        public static string CalibratorThirdStep {
            get {
                return ResourceManager.GetString("CalibratorThirdStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esp. Canino.
        /// </summary>
        public static string CanineSpace {
            get {
                return ResourceManager.GetString("CanineSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El dispositivo no se encuentra conectado. Esta operacion no puede continuar..
        /// </summary>
        public static string DeviceNotFoundError {
            get {
                return ResourceManager.GetString("DeviceNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrepancia Oseo-Dentaria.
        /// </summary>
        public static string DiscrepancyTitle {
            get {
                return ResourceManager.GetString("DiscrepancyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de Calculo!..
        /// </summary>
        public static string Error_CalculationError {
            get {
                return ResourceManager.GetString("Error_CalculationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error de cálculo. Por favor revise los valores provistos y vuelva a intentarlo..
        /// </summary>
        public static string Error_CalculationErrorOccurred {
            get {
                return ResourceManager.GetString("Error_CalculationErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de conexion!.
        /// </summary>
        public static string Error_Conexion {
            get {
                return ResourceManager.GetString("Error_Conexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El dispositivo no se encuentra conectado..
        /// </summary>
        public static string Error_DeviceNotFound {
            get {
                return ResourceManager.GetString("Error_DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error de aplicación. Por favor, póngase en contacto con el adminstrator..
        /// </summary>
        public static string Error_GeneralError {
            get {
                return ResourceManager.GetString("Error_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el índice de búsquedas en tablas. Por favor revise los valores provistos y vuelva a intentarlo..
        /// </summary>
        public static string Error_IndexNotFound {
            get {
                return ResourceManager.GetString("Error_IndexNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indice de table no encontrado..
        /// </summary>
        public static string Error_TableIndexNotFound {
            get {
                return ResourceManager.GetString("Error_TableIndexNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf.
        /// </summary>
        public static string ExportToPdf {
            get {
                return ResourceManager.GetString("ExportToPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indices Implantes.
        /// </summary>
        public static string Help_Implants {
            get {
                return ResourceManager.GetString("Help_Implants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indices Ortodoncia.
        /// </summary>
        public static string Help_Index {
            get {
                return ResourceManager.GetString("Help_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medir espacio disponible para Premolares,  Canino e Incisivos.
        /// </summary>
        public static string Help_Mouth {
            get {
                return ResourceManager.GetString("Help_Mouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cada segmento representa el espacio disponible, no el ancho de las piezas. Los segmentes no deben superponerse.
        /// </summary>
        public static string Help_Mouth2 {
            get {
                return ResourceManager.GetString("Help_Mouth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Resultados.
        /// </summary>
        public static string Help_ResultsButton {
            get {
                return ResourceManager.GetString("Help_ResultsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empezar a medir.
        /// </summary>
        public static string Help_SampleButton {
            get {
                return ResourceManager.GetString("Help_SampleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medir ancho mesio-distal de cada pieza dentaria.
        /// </summary>
        public static string Help_Theet {
            get {
                return ResourceManager.GetString("Help_Theet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esp. Incisivos.
        /// </summary>
        public static string IncisivesSpace {
            get {
                return ResourceManager.GetString("IncisivesSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inferior:.
        /// </summary>
        public static string Inferior {
            get {
                return ResourceManager.GetString("Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceso Inferior:.
        /// </summary>
        public static string InferiorExcess {
            get {
                return ResourceManager.GetString("InferiorExcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incisivos Inferior:.
        /// </summary>
        public static string InferiorIncisives {
            get {
                return ResourceManager.GetString("InferiorIncisives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inferiores:.
        /// </summary>
        public static string InferiorPlurarl {
            get {
                return ResourceManager.GetString("InferiorPlurarl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izquierdo:.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrar.
        /// </summary>
        public static string Menu_Calibrator {
            get {
                return ResourceManager.GetString("Menu_Calibrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indices.
        /// </summary>
        public static string Menu_Index {
            get {
                return ResourceManager.GetString("Menu_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha:.
        /// </summary>
        public static string MessureDate {
            get {
                return ResourceManager.GetString("MessureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero HC:.
        /// </summary>
        public static string MessureHCNumber {
            get {
                return ResourceManager.GetString("MessureHCNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paciente:.
        /// </summary>
        public static string MessurePatient {
            get {
                return ResourceManager.GetString("MessurePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesional:.
        /// </summary>
        public static string MessureProfessional {
            get {
                return ResourceManager.GetString("MessureProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moyers (Prediccion de discrepancias).
        /// </summary>
        public static string MoyerTitle {
            get {
                return ResourceManager.GetString("MoyerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pont.
        /// </summary>
        public static string PontTitle {
            get {
                return ResourceManager.GetString("PontTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esp. Premolares.
        /// </summary>
        public static string PremolarSpace {
            get {
                return ResourceManager.GetString("PremolarSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolton Anterior  -&gt;.
        /// </summary>
        public static string PreviousBolton {
            get {
                return ResourceManager.GetString("PreviousBolton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derecho:.
        /// </summary>
        public static string Rigth {
            get {
                return ResourceManager.GetString("Rigth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior:.
        /// </summary>
        public static string Superior {
            get {
                return ResourceManager.GetString("Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceso Superior:.
        /// </summary>
        public static string SuperiorExcess {
            get {
                return ResourceManager.GetString("SuperiorExcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superiores:.
        /// </summary>
        public static string SuperiorPlural {
            get {
                return ResourceManager.GetString("SuperiorPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtener Muestras.
        /// </summary>
        public static string TakeSample {
            get {
                return ResourceManager.GetString("TakeSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanaka.
        /// </summary>
        public static string TanakaTitle {
            get {
                return ResourceManager.GetString("TanakaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14 a 24:.
        /// </summary>
        public static string To24 {
            get {
                return ResourceManager.GetString("To24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 a 26:.
        /// </summary>
        public static string To26 {
            get {
                return ResourceManager.GetString("To26", resourceCulture);
            }
        }
    }
}
